project:
  type: website
  render:
    - README.md
    - topics/**/*.ipynb
  preview:
    port: 4200
    browser: false

execute:
  freeze: auto

format:
  html:
    lightbox: true
    html-math-method: katex
    respect-user-color-scheme: true
    highlight-annotations: true
    highlight-style: dracula
    toc: true
    toc-location: right
    theme:
      light: [cosmo, assets/theme.scss]
      dark:  [cosmo, assets/theme-dark.scss]
    css: assets/styles.css

website:
  title: "particle1331/ai-notebooks"
  repo-url: https://github.com/particle1331/ai-notebooks
  site-url: https://particle1331.github.io/ai-notebooks/
  back-to-top-navigation: true
  favicon: assets/robot.jpg
  page-navigation: true
  bread-crumbs: true
  reader-mode: true

  navbar:
    left:
      - text: "README"
        href: index.html
      - text: "Topics"
        menu:
          - text: "Deep Learning"
            href: topics/deep/index.html
          - text: "Tooling"
            href: topics/tooling/index.html
          
    tools:
      - icon: github
        href: https://github.com/particle1331/ai-notebooks
        text: GitHub

  sidebar:
    - id: deep
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - section: "Deep Learning"
          href: topics/deep/index.ipynb
          contents: topics/deep/*.ipynb
        # - section: "CUDA Programming"

    - id: tooling
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - section: "Tooling"
          href: topics/tooling/index.ipynb
          contents: topics/tooling/*.ipynb
