project:
  type: website
  render:
    - README.md
    - notebooks/**/*.ipynb
  preview:
    port: 4200
    browser: false
  resources:
    - notebooks/apps/img/**/*

bibliography: assets/references.bib

execute:
  freeze: auto

format:
  html:
    lightbox: true
    html-math-method: katex
    highlight-annotations: true
    toc: true
    toc-location: right
    theme: united
    # highlight-style: dracula
    # theme:
    #   light: [cosmo, assets/theme.scss]
    #   dark:  [cosmo, assets/theme-dark.scss]
    css: assets/styles.css

website:
  title: "particle1331/ai-notebooks"
  repo-url: https://github.com/particle1331/ai-notebooks
  site-url: https://particle1331.github.io/ai-notebooks/
  back-to-top-navigation: true
  favicon: assets/robot.jpg
  page-navigation: true
  bread-crumbs: true
  reader-mode: true

  navbar:
    left:
      - text: "README"
        href: index.html
      - text: "Topics"
        menu:
          - text: "Deep Learning Foundations"
            href: notebooks/deep/index.html
          - text: "Language Models From Scratch"
            href: notebooks/llm/index.html
          - text: "Agentic Systems"
            href: notebooks/agents/index.html
          - text: "App Development"
            href: notebooks/apps/index.html
          - text: "Special Topics & Tooling"
            href: notebooks/tooling/index.html

    tools:
      - icon: github
        href: https://github.com/particle1331/ai-notebooks
        text: GitHub

  sidebar:
    - id: deep
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: ""
          href: notebooks/deep/index.ipynb
          contents: notebooks/deep/*.ipynb
        # - section: "CUDA Programming"
        # recsys
        # deep RL

    - id: llm
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: ""
          href: notebooks/llm/index.ipynb
          contents: notebooks/llm/*.ipynb
 
    - id: tooling
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: ""
          href: notebooks/tooling/index.ipynb
          contents: notebooks/tooling/*.ipynb

    - id: agents
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: ""
          href: notebooks/agents/index.ipynb
          contents: notebooks/agents/*.ipynb

        - section: ""
          href: notebooks/agents/patterns/index.ipynb
          contents: notebooks/agents/patterns/*.ipynb

    - id: apps
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - section: ""
          href: notebooks/apps/index.ipynb
          contents: notebooks/apps/*.ipynb
