project:
  type: website
  render:
    - README.md
    - topics/**/*.ipynb
  preview:
    port: 4200
    browser: false

execute:
  freeze: auto

format:
  html:
    respect-user-color-scheme: true
    toc: true
    toc-location: right
    theme:
      light: [cosmo, assets/theme.scss]
      dark:  [cosmo, assets/theme-dark.scss]
    css: assets/styles.css
    html-math-method: katex


website:
  title: "particle1331/ai-notebooks"
  repo-url: https://github.com/particle1331/ai-notebooks
  site-url: https://particle1331.github.io/ai-notebooks/
  back-to-top-navigation: true
  favicon: assets/robot.jpg
  page-navigation: true
  bread-crumbs: true
  reader-mode: true

  navbar:
    left:
      - text: "README"
        href: index.html
      - text: "Topics"
        menu:
          - text: "Deep Learning Systems"
            href: topics/dlsys/index.html
          - text: "Machine Learning in C++"
            href: topics/cpp/index.html
          
    tools:
      - icon: github
        href: https://github.com/particle1331/ai-notebooks
        text: GitHub

  sidebar:
    - id: dlsys
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - section: "Deep Learning Systems"
          href: topics/dlsys/index.ipynb
          contents: topics/dlsys/*.ipynb
